### ISSUE TITLE
Issues with page push dropping lines

### ISSUE THREAD

**Issue by Steptornetta** [skuid/skuid-sfdx#26]
Hello - not sure if this repo is still being monitored but I noticed and issue I am having with the page:push command dropping lines/characters in my XML. I think this may be related to a salesforce limitation, but I am not entirely sure. 

The page in question has:
- Lines: 7410
- Characters: 427359

This is the only page I have noticed the issue with, so I am assuming it has something to do with the size. 

If I run the page:push command with trace logging on there is nothing to indicate anything went wrong with the push. Once I view the page in the page composer though I can see that it has XML tags that have been dropped causing the page to break.

Curious to see if anyone else has run into this?

**Comment by Rnhatch** [comment]
We do monitor this Repo - even though there has not been much activity lately.   You will get better response on our Community though.  (community.skuid.com). 

The reason your push is failing is because our Salesforce managed package implementation (What we call Skuid SFX)  has a size limit for pages.  You must have built this page in our fully hosted solution (what we call Skuid NLX or Skuid platform) and then tried to move it into a Salesforce implementation using the CLI.   

Because of the size limits on storing records in Salesforce,  the largest page you can save in Skuid SFX is 160,000 characters.    When we started we NEVER thought we'd see pages larger than that.  But alas - we do see them now and again. 

Here are some strategies you might use to "slim" the page: 
- Use our page include capabilites to break up the page and it can be pulled together at runtime to work correctly. 
- Or make sure any code assets (snippets and other JS files) are stored as static resources and not written directly in the page.

**Comment by Steptornetta** [comment]
@Rnhatch - Thanks for the quick response, Rob! I did notice playing around with the push command; I was able to get the page to successfully push without cutting off characters/lines by commenting out the condenser. Not sure if this is intended or not but it seemed to work?

All our apps/pages have been built within Skuid SFX and been maintained within Skuid SFX. We do not have NLX. 

That additionally why I thought this was strange. For example, I can copy and paste the page XML into the XML page editor in Skuid SFX and have no issues. The page:pull command also has no issues grabbing a page of this size. 

Thanks for the reminder about the static resources! We are using page include but haven't migrated our scripts over to separate resources yet.

`
        // Prior to sending the pages over the wire, condense the XML.
        // This prevents us from having to waste Apex processing time as well as network bandwidth.
        pageDefinitions.forEach(pageDefinition => {
            //pageDefinition.body = xml_1.condenseXml(pageDefinition.body);
        });

`
